# Generated by Django 3.0.1 on 2019-12-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
