# Generated by Django 3.0.1 on 2019-12-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klikerwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=1233124231, unique=True),
            preserve_default=False,
        ),
    ]
